# Generated by Django 4.0.4 on 2022-10-19 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='regform',
            old_name='email',
            new_name='Question',
        ),
        migrations.RenameField(
            model_name='regform',
            old_name='firstName',
            new_name='answer',
        ),
        migrations.RemoveField(
            model_name='regform',
            name='DOB',
        ),
        migrations.RemoveField(
            model_name='regform',
            name='lastName',
        ),
        migrations.RemoveField(
            model_name='regform',
            name='password',
        ),
        migrations.RemoveField(
            model_name='regform',
            name='username',
        ),
    ]
