# Generated by Django 4.0.4 on 2022-10-19 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0002_rename_email_regform_question_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regform',
            name='Question',
        ),
    ]
